version: 2
jobs:
  build:
    working_directory: ~/bn
    docker:
      - image: elixir:latest
    steps:
      - checkout

      - restore_cache:
         keys:
           - v1-dependency-cache-{{ arch }}-{{ checksum "mix.lock" }}
           - v1-dependency-cache-{{ arch }}
           - v1-dependency-cache

      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix deps.get

      - run: mix credo
      - run: mix format --check-formatted
      - run: mix test

      - save_cache:
          key: v1-dependency-cache-{{ arch }}-{{ checksum "mix.lock" }}
          paths:
            - _build
            - deps
            - ~/.mix

      - restore_cache:
          keys:
            - v1-plt-cache-{{ arch }}-{{ checksum "mix.lock" }}
            - v1-plt-cache-{{ arch }}-{{ checksum "mix.exs" }}
            - v1-plt-cache-{{ arch }}

      - run:
          name: Unpack PLT cache
          command: |
            mkdir -p _build/test
            cp plts/dialyxir*.plt _build/test/ || true
            mkdir -p ~/.mix
            cp plts/dialyxir*.plt ~/.mix/ || true

      - run: mix dialyzer --plt

      - run:
          name: Pack PLT cache
          command: |
            mkdir -p plts
            cp _build/test/dialyxir*.plt plts/
            cp ~/.mix/dialyxir*.plt plts/

      - save_cache:
          key: v1-plt-cache-{{ arch }}-{{ checksum "mix.lock" }}
          paths:
            - plts

      - save_cache:
          key: v1-plt-cache-{{ arch }}-{{ checksum "mix.exs" }}
          paths:
            - plts

      - save_cache:
          key: v1-plt-cache-{{ arch }}
          paths:
            - plts

      - run: mix dialyzer --halt-exit-status
